# Shimamura固有の検索・マージ依頼設定
task_report_settings:
  shimamura_search:
    target_status: "22.Upload check"  # この値のみコメント更新対象とする
    comment_template: |
      Please merge to schoolmng and send back to JP until [DATE_MD] 18:00.
      No need to upload the files.
      *Please write down all merged file pass on task report(not only folder name even for new folder)

      If there is conflict, do not merge and return the task report to Tokyo with detail information.
      Also please do not merge if need other task report which doesn't have merge request to merge together.

      If merge successed set  task report status to 08.Merged/upload Rq.
      otherwise set task report status to 94.MergeErr.

      *After commit to new environment please check DIFF for merged file between developed repository and merged repository.
      EX: Merge schoolmng_dev->schoolmng then check DIFF for same file between schoolmng_dev and schoolmng
      Save DIFF evidence to Google Drive below
      \philippines\01.Customers\Shimamura\07_merge_evidence\[DATE_YYYYMMDD]\xxxxx\  xxxxx=TRNo
      File name will be TRNo-MergeFrom-MergeTo
      EX:99999-schoolmng_dev-schoolmng.png

school_specific_defaults:
  s: 
    Project: "SMMs001PH"
    Title: "(UATxxx)-----(shimaXXs)"
    Comments: "sc"
  t:
    Project: "SMMN003PH"
    Title: "(UATxxx)-----(SMBCPOS21s)"
    Comments: "tc"
  h:
    Project: "SMMs001PH" # sと同じだが明示的に記述
    Title: "(UATxxx)-----(shimaXXs)"
    Comments: "hc"
  up:
    Category: "[KANKYOUMEI]環境_更新依頼"
    Title: "[KANKYOUMEI]環境_更新依頼"
    Comments: |
        下記のTRに紐づくschoolmngの資材を[KANKYOUMEI]環境へUPをお願いします。(TOTAL8)
        XXXXX
        XXXXX
        XXXXX
        
        今回事前事後対応がありま、、、
  sm:
    Project: "TCNz007PH"
    Title: "(MySQLVerUP対応)-----"
    Comments: "sc"
